webfj_django/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from webfj_django_doutu import urls as webfj_django_doutu_urls
from webfj_django_doutu import views
# from django.urls import path
# from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^index/rest_api/', include('webfj_django_apis.rest_api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'doutu/',views.)
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^users/', include('webfj_django_doutu.urls')),
    # url(r'^doutu/', include('webfj_django_doutu.urls')),

    url(r'^$', views.index, name='index'),
    url(r'^table_list/', include('webfj_django_apis.urls')),
    # url(r'^doutu/', include('webfj_django_doutu.views.list_doutu')),
]

webfj_django_doutu/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
# from django.views.generic.simple import *
from django.conf.urls import include

from . import views

app_name = 'webfj_django_doutu'

urlpatterns = [
    # url(r'^$', 'django.views.generic.simple.direct_to_template', {'template': 'index.html'}),
    # url(r'^doutu/', include('webfj_django_doutu.views.list_doutu')),
    # url(r'^$', views.index, name="index"),
    url(r'^register/', views.register, name="register")
    # url(r'^home/', views.home, name="home"),
]

webfj_django_doutu/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.

class TableManager(models.Manager):
    def query_by_id(self):
        query = self.get_queryset().order_by('-id')
        return query

@python_2_unicode_compatible
class NewUser(AbstractUser):
    profile = models.CharField('profile', default='', max_length=256)
    gender = models.CharField(max_length=5, choices=(('man', '男'), ('woman', '女')))

    class Meta(AbstractUser.Meta):
        pass

    def __str__(self):
        return self.username

@python_2_unicode_compatible
class Table(models.Model):
    objects = TableManager()
    title = models.CharField(max_length=50)
    img_url = models.CharField(max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'table'
        verbose_name_plural = 'table'

class Poll(models.Model):
    user = models.ForeignKey('NewUser', null=True)
    table = models.ForeignKey('Table', null=True)

webfj_django_doutu/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from .models import Table, Poll, NewUser
from webfj_django.forms import LoginForm, RegisterForm, SetInfoForm
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.views.decorators.cache import cache_page

import urlparse

def login(request):
    return render(request, '/')

def register(request):
    redirect_to = request.POST.get('next', request.GET.get('next', ''))

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()

            if redirect_to:
                return redirect(redirect_to)
            else:
                return redirect('/users/login')
    else:
        form = RegisterForm()
    return render(request, 'doutu/register.html', context={'form': form, 'next': redirect_to})

def index(request):
    """

    :param request:
    :return:
    """
    # doutu_list = Table.objects.query_by_id()
    # loginform = LoginForm()
    # context = {'doutu_list': doutu_list, 'loginform': loginform}
    # return render(request, 'index.html', context)
    return render(request, 'index.html')

# from models import NewUser

# Create your views here.
# def list_doutu(request):
    # doutu_list = Table.objects.order_by('-id')
    # doutu_list = Table.objects.all()
    # return render_to_response('doutu/doutu.html', {'doutu_list': doutu_list})

# def home(request):
    # return render_to_response('index.html')

webfj_django_doutu/templates/doutu/doutu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>doutu information</title>
</head>
<body>
{% for doutu in doutu_list %}
title: {{ doutu.title }}
img_url: {{ doutu.img_url }}
{% endfor %}
</body>
</html>

webfj_django_doutu/templates/doutu/register.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>注册</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h1><a href="{% url 'index' %}">doutu data page</a></h1>
                <h3>注册</h3>
                <form class="form" action="{% url 'webfj_django_doutu:register' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">注册</button>
                    <input type="hidden" name="next" value="{{ next }}"/>
                </form>
                <div class="flex-center top-gap text-small">
                    <a href="{% url 'login' %}">已有账号登录</a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>